<?php

namespace Home\Common;

use Think\Controller;

class BaseController extends Controller
{
    protected function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
        //在公共控制器的初始化方法中，创建一个常量用来判断用户是否登录或已登录
        define('USER_ID1', session('user_id'));
        define('USER_ID2', cookie('user_id'));
    }

    //判断用户是否登录
    protected function isLogin()
    {
        //如果登录常量为NULL,表示没有登录
        if (is_null(USER_ID1)) {
            if (is_null(USER_ID2)){
                $this->assign('is_login', 0);//0为未登录
            }else{
                $this->assign('is_login', 2);//2为持久登录
            }
        } else {
            $this->assign('is_login', 1);//1为已登录
        }
    }

//    //如果用户已经登录，将不允许再次登录
//    protected function alreadyLogin()
//    {
//        //如果登录常量为NULL,表示没有登录
//        if (!is_null(USER_ID1)) {
//            $this->error('请不要重复登录~~', '/Admin/index/index');
//        }
//    }
}